### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by linakherchi** [abelchiao/asana_clone#2]
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by linakherchi** [comment]
Thanks, Abel ! Can you clarify to me how you are going to access the array of taskIds belong to each project?

**Comment by abelchiao** [comment]
I was thinking that because sections belong to projects and the tasks belong to sections, I would use a through association to link tasks to their project and use Jbuilder to set the array of taskIds on the projects. 

The relationship between tasks and projects is kind of a fuzzy area - in the live app, tasks can be assigned to multiple projects (and therefore multiple project sections) but I'm only allowing them to be associated with a single project for the time being to simplify things and build out the minimum viable product. 

If you have any ideas for easier ways to handle/organize this I would love to hear them!
